### ISSUE TITLE
Login bug, missing pages and filter

### ISSUE THREAD

**Issue by Tohjuler** [Eltik/Anify#20]
Hi.

The login page is not working, it just shows me this.
![image](https://github.com/Eltik/Anify/assets/84204734/5d5699f7-4416-47d1-94ca-a5b8205c2bf4)
No Console or network errors.

I am pretty sure you already know this but the About and Teams of service link in the footer is just 404 pages.

The filters on the search page is not working as inteted.
![image](https://github.com/Eltik/Anify/assets/84204734/64aa7ce9-9e4b-482c-93b6-6ed2cf07ede8)

Best regards,
Tohjuler

**Comment by Eltik** [comment]
Hey sorry for the late reply. I fixed the drop down issue, but the login issue likely won't be fixed as I no longer maintain Anify. Thank you for opening this issue however! Feel free to join the [Discord](https://anify.tv/discord) if you have any questions.
